name: Benchmark Test

on: [ workflow_dispatch ]

jobs:
  benchmark:
    runs-on: macos-latest
    strategy:
      matrix:
        params:
          # Music21 is too slow, and we don't really care about the accuracy for music21
          #          - { library: "music21", repeat: 1 }
          - { library: "symusic", repeat: 128 }
          - { library: "midifile_cpp", repeat: 128 }
          - { library: "miditoolkit", repeat: 1 }
          - { library: "partitura", repeat: 1 }
          - { library: "pretty_midi", repeat: 1 }

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r ./requirements.txt
          pip install ./binding/midifile_cpp

      - name: Install partitura (development version)
        run: |
          bash ./script/install_partitura_dev.sh

      - name: Prepare the dataset
        # /dev/shm is a shared memory location that is faster than the disk
        # The full path to the dataset is /dev/shm/symusic_benchmark_datasets
        run: |
          python ./script/prepare_dataset.py --output ./

      - name: Log version information
        run: |
          python ./script/log_version.py --output ./results/version_info.json

      - name: Run the benchmark
        run: |
          python ./script/benchmark.py --libraries ${{ matrix.params.library }} --repeat ${{ matrix.params.repeat }} --dataset_root ./symusic_benchmark_datasets --dataset_config ./config/uniform_25_4.json --output ./results

#      - name: Upload the results
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ matrix.params.library }}
#          path: ./results/uniform_25_4/${{ matrix.params.library }}_read.csv
#            | ./results/uniform_25_4/${{ matrix.params.library }}_write.csv
#          if-no-files-found: 'warn'

      - name: Upload READ results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.params.library }}_read.csv
          path: ./results/uniform_25_4/${{ matrix.params.library }}_read.csv

      - name: Upload WRITE results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.params.library }}_write.csv
          path : ./results/uniform_25_4/${{ matrix.params.library }}_write.csv

      - name: Upload the version information
        if: ${{ matrix.params.library == 'symusic' }}
        uses: actions/upload-artifact@v4
        with:
          name: version_info.json
          path: ./results/version_info.json

  visualize:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          pip install -r ./requirements.txt

      - name: Merge Artifact
        uses: actions/upload-artifact/merge@v4
        with:
          name: all_stats
          pattern: '*.csv'  # Merge all artifacts

      - name: Download the merged artifact
        uses: actions/download-artifact@v4
        with:
          name: all_stats
          path: ./stats

      - name: Visualize the results
        run: |
          python ./script/visualize.py --input ./stats --output ./fig
          ls -l ./fig

      - name: Upload the visualization
        uses: actions/upload-artifact@v4
        with:
          name: fig
          path: ./fig/*.png