name: Benchmark

on: [workflow_dispatch]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          pip install -r ./requirements.txt
          pip install ./binding

      - name: Run benchmark
        run: |
          python ./benchmark.py

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          path: "*.csv"