name: Benchmark

on: [workflow_dispatch]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        library: [symusic, midifile_cpp, mido, miditoolkit, pretty_midi, partitura]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r ./requirements.txt
          pip install ./binding/midifile_cpp

      - name: Install partitura (development version)
        run: |
          bash ./script/install_partitura_dev.sh

      - name: Prepare the dataset
        # /dev/shm is a shared memory location that is faster than the disk
        # The full path to the dataset is /dev/shm/symusic_benchmark_datasets
        run: |
          python ./script/prepare_dataset.py --output /dev/shm/

      - name: Log version information
        run: |
          python ./script/log_version.py --output ./results/version_info.json